-- Create sample organizations
INSERT INTO organizations (id, name, description, mission, email, phone, address, city, state, zip_code, verified, type, size, founded_year, created_at) VALUES
  ('org_1', 'Green Portland Initiative', 'A community-focused environmental organization dedicated to creating a more sustainable Portland through education, action, and advocacy.', 'To build a sustainable future for Portland through community engagement and environmental stewardship.', 'info@greenportland.org', '(503) 555-0123', '1234 Eco Street', 'Portland', 'OR', '97201', true, 'NONPROFIT', 'MEDIUM', 2015, NOW() - INTERVAL '2 years'),
  ('org_2', 'Portland Education Alliance', 'Supporting educational excellence and equity in Portland schools through tutoring, mentoring, and resource provision.', 'To ensure every student in Portland has access to quality education and the support they need to succeed.', 'contact@portlandedu.org', '(503) 555-0456', '5678 Learning Lane', 'Portland', 'OR', '97202', true, 'NONPROFIT', 'LARGE', 2008, NOW() - INTERVAL '3 years'),
  ('org_3', 'Helping Hands Network', 'A volunteer-driven organization focused on addressing food insecurity and supporting vulnerable populations in our community.', 'To eliminate hunger and provide support to those in need through community collaboration and compassion.', 'volunteers@helpinghands.org', '(503) 555-0789', '9012 Care Circle', 'Portland', 'OR', '97203', true, 'NONPROFIT', 'SMALL', 2012, NOW() - INTERVAL '1 year'),
  ('org_4', 'Digital Inclusion Network', 'Bridging the digital divide by providing technology education and support to underserved communities.', 'To ensure everyone has access to technology and the skills needed to thrive in the digital age.', 'hello@digitalinclusion.org', '(503) 555-0321', '3456 Tech Avenue', 'Portland', 'OR', '97204', false, 'NONPROFIT', 'SMALL', 2020, NOW() - INTERVAL '6 months'),
  ('org_5', 'Habitat for Humanity Portland', 'Building homes, communities, and hope by bringing people together to create affordable housing solutions.', 'A world where everyone has a decent place to live.', 'info@habitatportland.org', '(503) 555-0654', '7890 Build Boulevard', 'Portland', 'OR', '97205', true, 'NONPROFIT', 'LARGE', 1985, NOW() - INTERVAL '5 years');

-- Create sample volunteer opportunities
INSERT INTO volunteer_opportunities (id, title, description, requirements, responsibilities, benefits, start_date, end_date, location, address, city, state, zip_code, max_spots, skills, categories, status, organization_id, created_at) VALUES
  ('opp_1', 'Community Garden Cleanup', 'Join us for a morning of planting, weeding, and harvesting in our community garden. All skill levels welcome! Tools and refreshments provided.', 'No experience necessary. Must be able to work outdoors and perform light physical activity.', 'Weeding garden beds, planting new vegetables, harvesting produce, general cleanup and maintenance.', 'Learn about sustainable gardening, meet like-minded community members, enjoy fresh air and exercise.', NOW() + INTERVAL '3 days', NOW() + INTERVAL '3 days' + INTERVAL '4 hours', 'Laurelhurst Community Garden', '1234 Garden Way', 'Portland', 'OR', '97214', 25, ARRAY['Gardening', 'Physical Labor'], ARRAY['environment'], 'ACTIVE', 'org_1', NOW() - INTERVAL '2 days'),
  
  ('opp_2', 'Tree Planting Event', 'Help us plant native trees in Forest Park to restore habitat and combat climate change. This is a great opportunity for families and groups.', 'Comfortable with outdoor work. Minors must be accompanied by an adult.', 'Digging holes, planting trees, mulching, carrying supplies.', 'Contribute to environmental restoration, learn about native species, community service hours.', NOW() + INTERVAL '10 days', NOW() + INTERVAL '10 days' + INTERVAL '6 hours', 'Forest Park', '5678 Forest Drive', 'Portland', 'OR', '97210', 40, ARRAY['Gardening', 'Physical Labor', 'Teamwork'], ARRAY['environment'], 'ACTIVE', 'org_1', NOW() - INTERVAL '1 day'),
  
  ('opp_3', 'Math Tutoring Program', 'Provide one-on-one math tutoring for high school students. Help students build confidence and improve their academic performance.', 'Strong math skills (algebra, geometry, calculus). Teaching or tutoring experience preferred but not required.', 'Work with individual students, explain math concepts, help with homework, track student progress.', 'Make a direct impact on student success, develop teaching skills, flexible scheduling.', NOW() + INTERVAL '1 week', NOW() + INTERVAL '3 months', 'Roosevelt High School', '1234 Education Blvd', 'Portland', 'OR', '97202', 15, ARRAY['Teaching', 'Mathematics', 'Mentoring'], ARRAY['education'], 'ACTIVE', 'org_2', NOW() - INTERVAL '3 days'),
  
  ('opp_4', 'Food Bank Sorting', 'Sort and package food donations for distribution to families in need. This is ongoing work that makes a real difference in our community.', 'Ability to stand for extended periods and lift up to 25 pounds.', 'Sort donated food items, check expiration dates, package food boxes, maintain clean work area.', 'Direct impact on food security, meet other volunteers, learn about community needs.', NOW() + INTERVAL '5 days', NOW() + INTERVAL '5 days' + INTERVAL '4 hours', 'SE Portland Warehouse', '9012 Distribution Drive', 'Portland', 'OR', '97206', 30, ARRAY['Organization', 'Physical Labor'], ARRAY['food'], 'ACTIVE', 'org_3', NOW() - INTERVAL '4 days'),
  
  ('opp_5', 'Senior Technology Help', 'Help senior community members learn to use smartphones, tablets, and computers. Patient and friendly volunteers needed.', 'Basic computer skills, patience, good communication skills.', 'Provide one-on-one tech support, teach basic computer skills, help with smartphone setup.', 'Intergenerational connection, develop teaching skills, make technology accessible.', NOW() + INTERVAL '2 weeks', NOW() + INTERVAL '2 weeks' + INTERVAL '3 hours', 'Multnomah Community Center', '3456 Senior Street', 'Portland', 'OR', '97215', 10, ARRAY['Teaching', 'Technology', 'Patience'], ARRAY['education'], 'ACTIVE', 'org_4', NOW() - INTERVAL '1 week'),
  
  ('opp_6', 'Habitat Build Day', 'Help build affordable housing for local families. No construction experience required - we provide training and supervision.', 'Must be 16 or older. Safety-conscious and willing to follow instructions.', 'Framing, roofing, siding, painting, general construction tasks under supervision.', 'Learn construction skills, help families achieve homeownership, team building.', NOW() + INTERVAL '2 weeks', NOW() + INTERVAL '2 weeks' + INTERVAL '8 hours', 'SE Portland Build Site', '7890 Construction Court', 'Portland', 'OR', '97266', 20, ARRAY['Construction', 'Physical Labor', 'Teamwork'], ARRAY['construction'], 'ACTIVE', 'org_5', NOW() - INTERVAL '5 days');

-- Create sample volunteer applications
INSERT INTO volunteer_applications (id, user_id, opportunity_id, status, message, created_at) VALUES
  ('app_1', 'user_1', 'opp_1', 'PENDING', 'I have experience with gardening and would love to help with this project!', NOW() - INTERVAL '1 day'),
  ('app_2', 'user_2', 'opp_1', 'APPROVED', 'I am passionate about community gardens and have volunteered for similar projects before.', NOW() - INTERVAL '2 days'),
  ('app_3', 'user_6', 'opp_2', 'PENDING', 'I would like to help with the tree planting event. I have my own gardening tools I can bring.', NOW() - INTERVAL '1 day'),
  ('app_4', 'user_1', 'opp_3', 'APPROVED', 'I have a math degree and experience tutoring students. I would love to help.', NOW() - INTERVAL '3 days'),
  ('app_5', 'user_2', 'opp_4', 'PENDING', 'I am available to help with food sorting and have volunteered at food banks before.', NOW() - INTERVAL '2 days'),
  ('app_6', 'user_6', 'opp_5', 'APPROVED', 'I work in tech and enjoy helping seniors learn new technology.', NOW() - INTERVAL '4 days');

-- Update organizations with admin users
UPDATE organizations SET admin_id = 'user_1' WHERE id = 'org_1';
UPDATE organizations SET admin_id = 'user_2' WHERE id = 'org_2';
UPDATE organizations SET admin_id = 'user_6' WHERE id = 'org_3';
